name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'

      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}

      - name: Get Release URL (Tag)
        id: get_tag_release_url
        if: github.ref_type == 'tag'
        run: |
         curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/releases/tags/${{env.BRANCH_NAME}}
      
      - name: Print Info
        if: github.ref_type == 'tag'
        run: | 
         echo ${{steps.get_tag_release_url.outputs}}
         exit 1
     

  generate_build_installers:
    name: Generate Release Installers
    needs: build-job
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-20.04, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
       - name: Checkout Code Repository
         uses: actions/checkout@v4
         with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
    
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
            distribution: 'adopt'
            java-version: '21'

       - name: Composite Action
         uses: ./.github/composite
         with:
            branch_name: ${{ needs.release.outputs.RELEASE_VERSION }}
            isSnapshot: "false"
            release_upload_url: ${{ needs.release.outputs.RELEASE_UPLOAD_URL }}
            pom_version: ${{ needs.release.outputs.RELEASE_VERSION }}
            github_token: ${{secrets.GITHUB_TOKEN}}
            operating_system: ${{matrix.os}}
        

