name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  MAVEN_SETTINGS: '/home/ec2-user/maven/.m2/settings.xml'

jobs:
  build-job-ikmdev:
    name: Build Job (IKMDEV)
    runs-on: self-hosted
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
      
      - name: Maven Build
        if: env.BRANCH_NAME == 'main'
        run: |
            ./mvnw clean install \
                -s ${{env.MAVEN_SETTINGS}} \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
      
      - name: Maven Build -- Feature Branch
        if: env.BRANCH_NAME != 'main'
        run: |
            ./mvnw clean install \
                -s ${{env.MAVEN_SETTINGS}} \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -Denforcer.skip=true \
                -PcodeQuality

  build-job-forked:
    name: FoBuild Job 
    runs-on: self-hosted
    if: github.repository_owner != 'ikmdev'
    steps:
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
            java-version: '21'
            distribution: 'zulu'

       - name: Build IKMDEV Code
         uses: ikmdev/maven-clean-install-build-action@main
         with:
          branch_name: ${{env.BRANCH_NAME}}

      